<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NewFile1.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GTE.Clients\GTE.Clients.csproj" />
    <ProjectReference Include="..\GTE.DTOs\GTE.DTOs.csproj" />
    <ProjectReference Include="..\GTE.Auth.WindowsForms\GTE.Auth.WindowsForms.csproj" />
  </ItemGroup>

</Project>